class newsListBottom {
  String img,title,author,desc1,desc2,desc3,time,id;

  newsListBottom({
    this.img,
    this.title,
    this.author,
    this.desc1,
    this.desc2,
    this.desc3,
    this.time,
    this.id
  });
}

List<newsListBottom> newsList = [    
newsListBottom(
  id: "1",
img: "assets/image/News_Image/Asia.jpg",
title: "Asia Week: S Korean Crypto Chaos, Japanese Gamers’ Blockchain Bid",
author: "By Tim Alper",
time: "Yesterday",
desc1: "Meanwhile, newspaper Munhwa Ilbo says that cryptocurrency controversy has even divided families, with many married couples seriously considering divorce as a result of clandestine cryptocurrency investments. \n\n Other experts have urged the government “not to kill of the fourth industrial revolution” with potentially stifling regulations. \n\n Crypto has sparked a fierce public debate in the country, with government officials and academics taking it in turn to demonize and/or celebrate its virtues. Former health minister Rhyu Si-min sparked fury from all corners when he appeared on TV network JTBC’s popular Newsroom show, announcing, “Cryptocurrency speculation is spreading like wildfire and should be eliminated.”",
desc2: "Young South Koreans Bemoan Cryptocurrency Fate \n\n South Koreans in their twenties and thirties could be among those worst hit by the government’s proposed cryptocurrency clampdown. Per Korean exchanges Bitsum and Upbit, 70% of cryptocurrency investors in the country are aged 20-39. \n\nSpeaking in November last year, Park Sang-ki, South Korea’s justice minister, sent crypto markets around the world into a tailspin when he announced, “The government plans to close cryptocurrency exchanges and there is no disagreement between the ministries on this matter.”\n\nMedia outlets have been giving voice to frustrated young Koreans who have seen tighter regulations imposed on their trading – as well as the looming threat of the closure of the country’s cryptocurrency exchanges.\n\nThe ban has yet to materialize, but prices have tumbled as a result, with internet users dubbing price drops “a ceaseless storm of crap from above.” The “above” in this case pointedly refers to the government.",
desc3: "Japanese Gaming Giant Moves to Develop Blockchain Trading Platform\n\nGaming company Mobile Factory founder and CEO Miyajima Yuji has announced that his company is planning to move into the world of blockchain technology. Mobile Factory boasts popular title like Station Memories and Rekishi to Connect, and also provides a range of cell phone-related services, such as ringtones and mobile fortune-telling.\n\nSpeaking at the Japan Securities Analysts Association, Miyajima said, “Blockchain-related services are now a major challenge for the future.”He added that Mobile Factory has already taken “its first step” toward blockchain services deployment, with plans for a blockchain-powered game now in the pipelines. The game is set to debut sometime this year.\n\nMiyajima says the company hopes to introduce a blockchain-powered, decentralized trading platform for the game, along with a new, specially developed cryptocurrency that can be bought and sold on the platform."
),
newsListBottom(
  id: "2",
img: "assets/image/News_Image/EOSget.jpg",
title: "AEOS Gets New Update for Better Transaction Speed",
author: "By Sead Fadilpašić",
time: "Yesterday",
desc1: "Block.one, the company behind blockchain platform EOSIO, has announced that they’re releasing latest update to the code, which is said to allow for much greater speeds across the network than previously seen. According to the company, EOSIO 1.6.0 has reached up to 35% better transaction processing speed in internal testing. \n\nEOSIO, a platform for the execution of smart contracts and the building of decentralized applications (dapps), claims to have current maximum speeds recorded on its blockchain at 3,996 transactions per second. Aside from the higher speed, the update also includes reductions in CPU costs and decreased latency, making for cheaper running of applications as well as increasing their responsiveness",
desc2: "Block.one CEO Brendan Blumer said for the press release, “Our aim is to drive mass adoption of blockchain. As part of the community that continues to work on the EOSIO software and its corresponding advancements, we hope to play a leading role in the next generation of blockchains through our deep engineering talent and our dedication to a future of global commerce and communications based on blockchain. \n\nEOS, the EOSIO platform’s native token, is currently ranked 5th by market capitalization on coinmarketcap.com, worth USD 2.48 per coin.",
desc3: "The fight for speed on the blockchain is hardly unique for EOSIO. In fact, most other smart contract platforms, such as NEO, Qtum and others are participating in the race. Also, Ethereum’s upcoming Constantinople upgrade boasts four Ethereum Improvement Proposals (EIPs), three of which target speed, efficiency and scalability.\n\nMeanwhile, QtumX, an enterprise-level blockchain system developed by the Qtum team, has recently announced that according to benchmark testing, they can handle more than 10,000 transactions per second. “[QtumX] aims to realize high TPS (Transactions Per Second) and low confirmation time of the blockchain, to make dapps applicable to more business scenarios. Meanwhile, we intend to minimize storage and network consumption, so as to reduce operating costs,” the team announced this week."
),
newsListBottom(
  id: "3",
img: "assets/image/News_Image/YouCan.jpg",
title: "You Can Now Buy Crypto with Your Card on Binance",
author: "By Sead Fadilpašić",
time: "Yesterday",
desc1: "Major cryptocurrency exchange Binance now lets their users buy crypto assets by using their Visa and MasterCard debit and credit cards, made available through the exchange’s partnership with payment processor Simplex.\n\nThe coins that will be available for purchase this way are Bitcoin (BTC), Ethereum (ETH), Litecoin (LTC), and Ripple (XRP).\n\nAs the benefits of using cards to purchase cryptocurrencies, the Binance team states in its press release: “Fast: Average 10-30 mins for cryptocurrency to reach your wallet; Low Fees: only 3.5% per transaction or 10 USD, whichever is higher; Convenient: Visa and MasterCard accepted.”",
desc2: "Changpeng “CZ” Zhao, CEO of Binance, said that as we add more options, the fee will come down.\n\nNow, if you are not using BNB (Binance Coin) to pay your trading fees, each trade will carry a standard fee of 0.1%, according to the website of the exchange.\n\nChangpeng “CZ” Zhao, CEO of Binance, said in the official release, “We want to provide Binance traders with fast and easy access to crypto, in the most secure way possible,” later adding, “The crypto industry is still in its early stages and most of the world’s money is still in fiat. Building fiat gateways is what we need now to grow the ecosystem, increase adoption and introduce crypto to more users.”\n\nAlso, according to the CEO, Simplex does not support all credit cards, but do have a decent coverage.",
desc3: "Debt-incurring credit card usage in crypto has always been controversial. Perhaps most notably, top exchanges have gone back and forth on support. Cryptocurrency exchange Coinbase, for example, stopped allowing credit card purchases in the US a year ago but, when it still allowed them, customers were found to have incurred additional charges. However, that exchange still accepts credit and debit cards for those outside the US, as well as bank account transfers.\n\nAnother big setback is that banks are unsure whether they want to allow their clients to use their cards for crypto purchases. Lloyds Bank in the UK, for instance, banned their clients from making crypto purchases last year, following in the footsteps of JP Morgan and Citigroup. Australia’s largest retail-aimed bank, The Commonwealth, also said it would not allow its customers to buy digital assets using Commbank credit cards “due to the unregulated and highly volatile nature of virtual currencies.”"
),
newsListBottom(
  id: "4",
img: "assets/image/News_Image/Ziliqa.jpg",
title: "Zilliqa Launches First Public Sharding Blockchain",
author: "By Sead Fadilpašić",
time: "Yesterday",
desc1: "Blockchain project Zilliqa (ZIL) has launched its mainnet, heralded the first ever successful implementation of a scaling technology called sharding on a blockchain.\n\n“Today, we are taking a leap towards our vision of enabling innovative blockchain-powered solutions to real-world problems,” Zilliqa CEO and co-founder Xinshu Dong wrote in a blog post. “With this launch, Zilliqa is now the first public blockchain platform to successfully implement sharding, to address one of the biggest challenges to mainstream blockchain adoption – scalability.”",
desc2: "The launch of the Zilliqa mainnet means that sharding is possible in reality. This is also important for projects such as Ethereum, which is looking into sharding as one of the possible solutions to its scaling debate, although it is not expected on the Ethereum mainnet before 2020. With Zilliqa’s mainnet up and running, they may be lighting the way for other projects to implement this solution without forgoing security and decentralization while gaining scalability.\n\nAlthough there are many features that set Zilliqa apart from similar projects, sharding is considered by far the most important one, as the first live implementation of the technology. In general, sharding is a type of database partitioning that separates very large databases into smaller, faster, more easily managed parts called data shards.",
desc3: "In blockchain, sharding splits the work that the network has to do into smaller groups, called shards. Participants in the network (nodes) then establish consensus in those smaller groups, which makes transactions faster and cheaper than if they were processed by the entire network. In effect, it is a way of distributing the workload so that not every node has to do every task, like it happens with Bitcoin.\n\nBlockchain enthusiasts and developers can track the operations of the network via Zilliqa Explorer.\n\nHowever, the ZIL coin dropped sharply after the mainnet launch announcement, from around USD 0.018 before the news, to USD 0.017 after them. The price has recovered in the meantime, with a net decrease of around 0.9% in the past 24 hours (UTC 2:00 PM.) The coin is currently ranked 32nd by market capitalization."
),
newsListBottom(
  id: "5",
img: "assets/image/News_Image/BlockStream.jpg",
title: "Blockstream Aims to Help Exchanges to Prove their Reserves",
author: "By Tim Alper",
time: "Yesterday",
desc1: "Removing the need to trust anyone has been one of the biggest goals of cryptocurrencies. This should include cryptocurrency exchanges as much as any other party. That’s why major blockchain technology company Blockstream is building a tool called Proof of Reserve that allows an exchange to prove how many Bitcoin they could spend without needing to generate a “live” transaction or exposing themselves to the risks of moving funds\n\nThe idea behind Proof of Reserve is very simple, according to a blog post published by Blockstream. By using this tool, the exchange constructs a transaction made up of all their Bitcoin UTXOs (unspent transaction outputs) and adds an extra invalid input - in case the transaction is broadcast to the network by mistake, the invalid input will force the network to reject the whole transaction, preventing possible spending of the exchange’s funds. Still, the transaction data exists and can be shared with anyone asking for it in order to verify reserves.",
desc2: "The official blog post goes on to add, “Proof of Reserves is written in Rust [programming language,] and currently supports both the Bitcoin Core wallet and Trezor, with more integrations on the way (Ledger support coming soon!).” The team behind it is currently working on finding a way to disclose the sum of values without publicizing the value of individual UTXOs, which could possibly reveal too much information on each exchange’s financial operations.\n\nThe community also likes the idea of removing the need to trust exchanges without being provided proof. “Fantastic, really hope this gets picked up. Bitcoin hasn't seen exchanges do significant Proof of Reserves since right after the Mt Gox collapse in 2014,” tweeted Bitcoin fund Adamant Capital founder Tuur Demeester",
desc3: "At the moment, Blockstream has already submitted a BIP (Bitcoin Improvement Proposal) to the mailing list of Bitcoin developers and is waiting to receive feedback. Soon, the platform should be rolling out on Liquid, their inter-exchange settlement network linking together cryptocurrency exchanges and institutions around the world, where users can access a standard feature for proving Liquid Bitcoin (L-BTC) holdings.\n\nBut the Proof of Reserve solution is not a panacea. In a Twitter thread about the recent QuadrigaCX fiasco, blockchain architect Christopher Allen wrote, “Though I believe the loss of keys in this case to be a ruse, from my research for the #SmartCustody series of workshops a lot of what is being said by digital asset exchanges & custodians is security theater. Proof-of-Reserve is a good tool, but customers need demand more.”"
),
newsListBottom(
  id: "6",
img: "assets/image/News_Image/Mt.Gox.jpg",
title: "Mt. Gox and its Lords Without Rings",
author: "By Sead Fadilpašić",
time: "Yesterday",
desc1: "More than four years after the infamous Mt. Gox incident, where approximately 850,000 bitcoins belonging to customers and the cryptocurrency exchange were announced to be missing and likely stolen, victims have been filing rehabilitation claims and are now waiting to be reimbursed. However, it seems that they might need to wait even longer, as two different entities are slowing down the process: cryptocurrency company CoinLab, headed by CEO Peter Vessenes, and former child actor and crypto entrepreneur Brock Pierce.\n\nThe now-defunct cryptocurrency exchange has been awarded permission to begin the process for civil rehabilitation in June last year, by the Tokyo District Court. Among the claimants is also CoinLab with a claim for a whopping USD 15 billion (JPY 1.6 trillion), according to a photo of the claim shared by lawyer Daniel Kelman.",
desc2: "Kelman is one of the many who lost their bitcoins in the Mt. Gox crash. He has been actively involved in the Gox case since 2013. He does not formally represent anyone and maintains that he is a creditor, with the best interests for creditors as motivation for his actions.\n\nCoinLab does not have a case, Kelman believes: “My bet is that CoinLab is holding out for an initial court ruling. The trustee will motion to have the CoinLab's claim/suit dismissed in court in a summary judgement motion. These motions are seldom granted and are only appropriate in cases where the result is obvious and the court's time not wasted hearing the facts.\n\n“He blew his chance in late 2010 by turning down an offer from Jed McCaleb (co-founder of Stellar) to take over Mt. Gox. Seven months or so later he came back trying but failing to assert an ownership stake in Mt. Gox after Bitcoin has soared from USD 1 to USD 30,” Kelman said.”",
desc3: "Meanwhile, a new initiative dubbed Gox Rising is calling for a new, accelerated rehabilitation plan for creditors of Mt. Gox, with the long-term goal of rebooting the trading platform, and is led by crypto entrepreneur Brock Pierce. He says that their long-term aim is to reboot the platform as a “Gox or Mt. Gox” exchange - to rehabilitate not only lost funds, but the brand name and domain itself. The rebooted platform would reportedly be non-custodial, to minimize security liabilities.\n\nKelman agrees: “Similar to CoinLab's Peter Vessenes, Pierce harbors feeling of a missed opportunity of which he cannot let go. He tried and failed to acquire Mt. Gox in 2014, getting only so far as a letter-of-intent (LOI) which is clearly not an enforceable agreement but which Pierce apparently wants to litigate over nonetheless.”"
),
newsListBottom(
img: "assets/image/News_Image/CryptoBroker.jpg",
title: "This Crypto Brokerage to Make Money With Commission-free Trading",
author: "By Tim Alper",
time: "Yesterday",
desc1: "Founded by Wall Street and Silicon Valley entrepreneurs, crypto brokerage startup Voyager Digital, that serves as a tool to help users find the best prices for Bitcoin and other cryptocurrencies has just launched a mobile app for “commission-free trading of 18 of the largest and most liquid crypto assets.",
desc2: "“Voyager will institute a measured roll-out beginning with clients in Arizona, California, Illinois, Kentucky, Pennsylvania, Massachusetts, Missouri, Montana and Wisconsin, states in which residents are already approved to trade digital assets,” the press release reads. “As Voyager’s applications with more key states are approved, those wait listed users will be invited and on-boarded respectively, with a goal of ultimately having more than 40 approved states by the end of 2019.”",
desc3: "The company has previously gone public in Canada, starting trading on the Toronto Venture Exchange (TSX-V) under the ticker VYGR, as a result of a reverse merger reportedly valued at USD 60 million. Ehrlich said that the decision to go public is set to bring a higher level of trust from customers, adding, “By becoming a publicly traded entity, Voyager allows the traditional investing community to tap the public markets for exposure to this important asset class and financial utility that is built upon the technology of the future [...] This type of exposure will help more people become comfortable with the crypto market and ultimately increase widespread adoption.”"
),
newsListBottom(
  id: "7",
img: "assets/image/News_Image/MarketSentiment.jpg",
title: "Market Sentiment: Positivity Among Top Coins Is Taking Over",
author: "By Sead Fadilpašić",
time: "Yesterday",
desc1: "Out of the top 10 coins by market capitalization, six are above the negative line in terms of market sentiment, while one is in the neutral waters, according to Predicoin, a crypto market sentiment data analysis service. The average score comes up to 5.41, an improvement compared to last week (5.02.)\n\nMoreover, the market is in green today. Bitcoin just broke the USD 3.900 level (UTC 4:40 AM,) last time seen on January 10, while ether surpassed USD 146 and other top coins are registering gains of 6% - 22% in the past 24 hours.",
desc2: "Part of the improved sentiment surrounding Stellar comes possibly from its Stellar v10.2.0 release, which introduced many new stabilizing elements and added new technical features, launched on February 14th. However, the sentiment around the coin is still negative at 4.6 compared to last week’s 3.6.\n\nBitcoin Cash’s high weekly improvement score is also a surprise compared to last week, when it was the fastest dropping coin by sentiment score out of the top 10 - but it’s still far from winning, given that it now scored 4.6 total.\n\nAs of Monday (UTC 10:28 am), the clear winners of the week are Ethereum , Litecoin , Bitcoin and EOS. In the more neutral range are Binance Coin, Tether, and TRON, although the fact that their scores are not below 5 could arguably mean they are winners as well. Tether and TRON are newcomers compared to last week, when Bitcoin, Ethereum, Litecoin, EOS, and Binance Coin were the only ones on the winning list.",
desc3: "The company has previously gone public in Canada, starting trading on the Toronto Venture Exchange (TSX-V) under the ticker VYGR, as a result of a reverse merger reportedly valued at USD 60 million. Ehrlich said that the decision to go public is set to bring a higher level of trust from customers, adding, “By becoming a publicly traded entity, Voyager allows the traditional investing community to tap the public markets for exposure to this important asset class and financial utility that is built upon the technology of the future [...] This type of exposure will help more people become comfortable with the crypto market and ultimately increase widespread adoption.”"
),
newsListBottom(
  id: "8",
img: "assets/image/News_Image/NewCripto.jpg",
title: "New Crypto Fever! Everyone is Checking their iPhones for ₿",
author: "By Sead Fadilpašić",
time: "Yesterday",
desc1: "In the cryptoverse, where we’re all looking for signs of increased adoption with bated breath, even the smallest things can bring hype. Today we have a new one - it seems that almost everyone in the cryptoland is checking their iPhones for the Bitcoin symbol.",
desc2: "It looks like the Google keyboard on iPhones now has a Bitcoin sign when you long press the dollar sign, among all the other currencies. However, no one knows when exactly it was added and why Google's product is not available on Android phones.\n\nTo access it, make sure you’re using the Google keyboard, not just the default Apple one, and hold down the dollar symbol to see a pop up of several of the world’s major currency symbols. The Bitcoin symbol is located on the far left. Although the symbol shares some similarities with the Thai Baht currency, the Baht has a single line all the way through - as opposed to Bitcoin’s two lines at the top and bottom of the capital B.",
desc3: "Some enthusiasts have taken this to mean that adoption is coming - while more extreme ones already see a bull run in the future. Although this may not mean anything, a small sign of endorsement is certainly good, especially with the recent rally.\n\nHowever, this feature is not available on Android phones yet, and there is no indication that it could become available any time soon. Also, not every Google keyboard on iPhone offers this possibility, as users from Scandinavian countries as well as France claimed on Twitter that they could not find the option. Additionally, some users complain that when they click the symbol, it turns into ₱, the symbol for the Philippine Peso - but it is possible that this is just a temporary glitch."
),
newsListBottom(
  id: "9",
img: "assets/image/News_Image/BNB.jpg",
title: "BNB Beats the Market as Binance Released Chain, DEX Testnet (UPDATED)",
author: "By Linas Kmieliauskas",
time: "Yesterday",
desc1: "Major cryptocurrency exchange Binance released Binance Chain and DEX testnet for public testing today. BNB, the native token of the exchange, is up by more than 14% in the past 24 hours (UTC 08:40 AM) while other major coins show small gains or are in red. (Updates throughout the entire text.)\n\n Binance Chain is a new blockchain developed and released by Binance. Binance DEX is a high performance and user friendly platform built on top of Binance Chain, where users can create, issue and trade digital assets,the exchange announced in a blog post, adding that the Binance Chain Mainnet launch date will be announced at a later date.",
desc2: "Crypto fund Multicoin Capital, who owns BNB in its portfolio, in a new analysis claims that BNB, is dramatically undervalued, primarily because it is a novel asset with properties that many investors do not yet fully appreciate.\n\nWhile the cryptoverse is discussing how decentralized Binance DEX is, Changpeng Zhao (CZ), CEO of Binance, during a livestream on the Ivan on Tech Youtube channel Wednesday morning said that this debate is less meaningful as, according to him, main things to discuss are security, ease of use and freedom.\n\nAlso, previously he also admitted that Binance will have a lot of influence over the Binance Chain (Binance DEX is running on this blockchain) network and the validators. Moreover, the CEO said that the listing fee on the new exchange will be probably close to USD 100,000.",
desc3: "Some enthusiasts have taken this to mean that adoption is coming - while more extreme ones already see a bull run in the future. Although this may not mean anything, a small sign of endorsement is certainly good, especially with the recent rally.\n\nHowever, this feature is not available on Android phones yet, and there is no indication that it could become available any time soon. Also, not every Google keyboard on iPhone offers this possibility, as users from Scandinavian countries as well as France claimed on Twitter that they could not find the option. Additionally, some users complain that when they click the symbol, it turns into ₱, the symbol for the Philippine Peso - but it is possible that this is just a temporary glitch.\n\nHe goes on further to explain that less decentralized means that socially, we have a lot of influence - as people know that it’s called the Binance Chain and we’re one of the key contributors to the development of the technology."
),
newsListBottom(
  id: "10",
img: "assets/image/News_Image/Twitter.jpg",
title: "Crypto Twitter Battle: How Leaders of Top 20 Coins Rank",
author: "By Sead Fadilpašić",
time: "Yesterday",
desc1: "Although the classification of cryptocurrencies by their market capitalization is the simplest one (despite the fact that this metric has flaws,) you may have wondered how the cryptocurrencies would rank by the size of their respective communities on Twitter, especially when some of crypto stars are bragging about the number of their followers and buying ads to get more.",
desc2: "1. Tron: Justin Sun - 896,000 followers\n\ncontract platform Ethereum. “Now we are both [at] 832k [followers]. We started six year [sic] after you but we always know it is never too late.”\n\n2. Ethereum: Vitalik Buterin - 837,000 followers\n\nAlthough Ethereum is striving to be as decentralized as possible, its political centralization is a sticking point for many, and Vitalik is by far the most recognized person involved in the smart contract platform. He is also often considered one of the biggest authorities on all things blockchain - given that he started Ethereum at the age of 19, the community’s trust in him is hardly misplaced.",
desc3: "3. Bitcoin Cash: Roger Ver - 569,000 followers\n\nBitcoin Cash is yet another of those projects that has no real leader figure, but when you mention the name Roger Ver, chances are most people will ask you “Is that the Bitcoin Cash guy?” Well-known for his unmoving belief that Bitcoin Cash is the real vision of Bitcoin creator Satoshi Nakamoto, Ver’s opinions are often considered controversial - which is part of what makes him so popular.\n\n4. Bitcoin: Andreas M. Antonopoulos - 470,000 followers\n\nSelecting one single person to represent Bitcoin is hard. Nobody knows (at least we don't) who Satoshi Nakamoto is - so our choice was between Andreas M. Antonopoulos and Nick Szabo. Considering that the former is slightly more active and outspoken within the Bitcoin community, our choice fell on him. Best-known for his best-selling book Mastering Bitcoin, Antonopoulos is often the loudest voice in matters of decentralization."
),
newsListBottom(
  id: "11",
img: "assets/image/News_Image/CBOE.jpg",
title: "CBOE Puts Brakes on Bitcoin Futures",
author: "By Tim Alper",
time: "Yesterday",
desc1: "The Chicago Board Options Exchange (CBOE) has announced that its CFE futures exchange platform will not be adding a Bitcoin (XBT) futures contract this month. The exchange operator also says it is currently considering its future stance on cryptocurrency derivatives trading.\n\nAccording to an official release, the CFE operator stated, “The CFE is assessing its approach with respect to how it plans to continue to offer digital asset derivatives for trading. While it considers its next steps, the CFE does not currently intend to list additional XBT futures contracts for trading.”",
desc2: "Rival CME exchange last month announced it had hit a new record of 18,338 bitcoin futures contracts traded, equivalent to around USD 360 million – although figures from March have been significantly lower.\n\nMeanwhile, the Unites States’ top financial regulator, the Securities and Exchange Commission (SEC), is still deliberating whether or not to approve a Bitcoin exchange-traded fund (ETF), and some claim the latest CBOE decision does not bode well in this regard. MisterLister lamented on Twitter, “ETF approval can’t be further away at this point.",
desc3: "The exchange noted, however, that “currently listed XBT futures contracts remain available for trading” – meaning existing futures listed last month (XBTM19) will continue to run until June\n\nCryptocurrency enthusiasts on Twitter and Reddit speculated that low trading volumes and competitor success may have been contributing factors in the CBOE’s decision.\n\nRival CME exchange last month announced it had hit a new record of 18,338 bitcoin futures contracts traded, equivalent to around USD 360 million – although figures from March have been significantly lower."
),

];